### ISSUE TITLE
Gatsby Plugin Disqus Configuration

### ISSUE THREAD

**Issue by emmadigital** [tterb/gatsby-plugin-disqus#17]
**Summary**
I have installed disqus plugin https://github.com/tterb/gatsby-plugin-disqus to my theme, it shows the disqus widget in the blog posts but its not properly linking to the disqus account. I have used correct shortname. The comments are zero on all posts. Whereas there are comments on most of my posts.

**Relevant information**
Here is my disqus plugin configuration code https://github.com/emmadigital/ardalis-newsite/blob/master/src/templates/blog-post.js

**Comment by dheysonalves** [comment]
Yeah, somehow, for me too. It doesn't connect with the disqus account. I have done the documentation steps.

**Comment by tterb** [comment]
@emmadigital It looks like you're actually using [disqus-react](https://github.com/disqus/disqus-react) in the repository you linked, whereas this is a very similar package that just integrates some added Gatsby integration.
Since creating this package I've also become the primary contributor/maintainer of `disqus-react`, but for posterity I would ask that you either modify your theme to utilize this package or move your issue to the [disqus-react](https://github.com/disqus/disqus-react) repository.

**Comment by tterb** [comment]
Also, @Dheyson are you able to provide a link to a public repo that I can use to reproduce your issue?

**Comment by dheysonalves** [comment]
Hey @tterb, sorry, it is not public or open-source. But then, I moved to `disqus-react`, and it is working fine. In this package here, I followed the steps, adding the plugin in `gatsby-config.js`, and then using it with a component. But thank you for reply here :b.

**Comment by tterb** [comment]
@Dheyson No problem, I'm glad you were able to resolve your issue.
