### ISSUE TITLE
"Use DISQUS.reset instead of reloading embed.js please."

### ISSUE THREAD

**Issue by gianfaye** [tterb/gatsby-plugin-disqus#28]
Hello, I'm seeing this message on my console. I'm currently working on my local build.

```
Use DISQUS.reset instead of reloading embed.js please.
See https://help.disqus.com/customer/portal/articles/472107-using-disqus-on-ajax-sites
```

I followed the installation steps from here: https://www.gatsbyjs.org/packages/gatsby-plugin-disqus/

I'm not sure if this is a common problem, if this is rooted from my configuration or if it is an issue with the plugin.

Please let me know what details should I provide further. Thank you!

**Comment by tterb** [comment]
@gianfaye Thanks for the report!
This isn't a problem with your implementation because I've seen it as well, but I haven't had a chance to look into it too deeply so I'm not sure if this is an issue that can be solved within the plugin or if the message is being triggered incorrectly within the Disqus service.
I will look into this and try to track down what is causing the plugin to reload and see if I can trigger a `DISQUS.reset()` instead.

**Comment by tterb** [comment]
@gianfaye I've put up a PR(#29) that appears to address this issue on my local test site, but it would be great if you could confirm it fixes the issue on your end as well before I merge the changes.

**Comment by gianfaye** [comment]
> @gianfaye I've put up a PR(#29) that appears to address this issue on my local test site, but it would be great if you could confirm it fixes the issue on your end as well before I merge the changes.

hi @tterb I'm currently encountering an issue with yarn so I cannot proceed to pull the changes:
https://github.com/yarnpkg/yarn/issues/1610

You can proceed merging the changes so I can re-install the plugin. 

Thank you!
